import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="border-b">
          <div className="max-w-2xl mx-auto p-3 flex gap-4">
            <a href="/" className="underline">Home</a>
            <a href="/dashboard" className="underline">Dashboard</a>
            <a href="/entries/new" className="underline">New Entry</a>
          </div>
        </nav>
        {children}
        <footer className="border-t mt-6">
          <div className="max-w-2xl mx-auto p-3 text-sm opacity-70">
            &copy; {new Date().getFullYear()} Voice Journal
          </div>
        </footer>
      </body>
    </html>
  );
}
